CREATE USER bidsphere WITH ENCRYPTED PASSWORD 'bidsphere123';
CREATE DATABASE bidsphere OWNER bidsphere;

\connect bidsphere

ALTER SCHEMA public OWNER TO bidsphere;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO bidsphere;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO bidsphere;
GRANT ALL PRIVILEGES ON SCHEMA public TO bidsphere;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO bidsphere;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO bidsphere;

\i /docker-entrypoint-initdb.d/schema.sql
